disabled submit button when upload file
wpmetabox/meta-box pull request #1424
Opened 2022-03-01 11:00 UTC by nhatrangnet

2022-03-14 03:05 UTC, rilwis requested changes

2022-03-14 03:05 UTC, rilwis commented on js/file-upload.js
> +	var isClassicEditor = ( classicEditorBtn.length > 0 );
A nghĩ mình target đến nút submit thì có thể viết ngắn gọn lại trong cả trường hợp classic và frontend.

```js
$submitButtons = rwmb.$document.find( 'button[name="rwmb_submit"], #publish' );
```

Đến đoạn dưới thì chỉ cần:

```js
if ( rwmb.isGutenberg ) {
    wp.data.dispatch( 'core/editor' ).lockPostSaving( 'uploading-file' );
} else {
    $submitButtons.prop( 'disabled', true );
}
```

2022-03-14 03:23 UTC, nhatrangnet commented on js/file-upload.js
> +	var isClassicEditor = ( classicEditorBtn.length > 0 );
em học được 1 kỹ thuật mới, cảm ơn anh nhé

2022-03-16 03:06 UTC, rilwis requested changes

2022-03-16 03:06 UTC, rilwis commented on js/file-upload.js
> +		initUploader: function ( $this ) {
Hình như ko cần phải refer đến biến `$this` đâu e ạ, chỉ cần `this.$el` là được. E thử lại xem.

2022-03-16 03:06 UTC, rilwis commented on js/file-upload.js
> +		$submitButtons = rwmb.$document.find( 'button[name="rwmb_submit"], #publish' );
Đoạn code này cũng cần bỏ chứ nhỉ?

2022-03-17 01:40 UTC, merged