refactor: remove unused variable
wpmetabox/meta-box pull request #1583
Opened 2024-06-04 16:38 UTC by tanftw

2024-06-07 00:28 UTC, rilwis requested changes
Ở đây em mới update cho post, em xem và update cho cả term & user nữa nhé.

2024-06-07 00:28 UTC, rilwis commented on css/modal.css
> +    max-width: 800px;
Em remove `max-width` và để `width: 90%` cho rộng nhé. Thêm `border: none` nữa vì trên Firefox nó có border đen khoảng 3-4px.

2024-06-07 00:28 UTC, rilwis commented on js/post.js
>  					return;
Nếu luôn lấy được post ID theo như ở hàm `closeModalCallback` thì phần lấy object ID ở đây là thừa nhỉ? E xoá & test lại xem nhé.

2024-06-10 01:32 UTC, tanftw commented on css/modal.css
> +    max-width: 800px;
Ok done & tested

2024-06-10 01:33 UTC, tanftw commented on js/post.js
>  					return;
Đúng rồi a, e bỏ luôn callback rồi, kể cả phần set lại overflow cũng thừa vì wp chỉ scroll ở phần editor hoặc sidebar chứ ko scroll cả trang edit post.

2024-06-10 01:34 UTC, tanftw commented
> Ở đây em mới update cho post, em xem và update cho cả term & user nữa nhé.

Term & User chạy tốt, e đã test và ko vấn đề gì, có post là lỗi thôi.

2024-06-10 15:25 UTC, rilwis approved these changes

2024-06-10 15:26 UTC, merged