fix: field['std'] inside group
wpmetabox/meta-box pull request #1601
Opened 2024-08-21 09:10 UTC by tanftw

2024-08-25 10:20 UTC, rilwis commented on inc/field.php
> +			$clone = Arr::ensure( $field['std'] ?? [] );
`$field['std']` luôn được set nên dùng `??` là bị thừa.

2024-08-25 10:20 UTC, rilwis commented on inc/field.php
> +		$multiple = $field['multiple'] ?? false;
Chỗ này cũng thế, các settings của field đều được set rồi, nên dùng `??` đều bị thừa.

2024-08-26 01:22 UTC, tanftw commented on inc/field.php
> +			$clone = Arr::ensure( $field['std'] ?? [] );
Ok a, lúc test e tạo trường hợp ko có std nên quên mất.

2024-08-26 01:22 UTC, tanftw commented on inc/field.php
> +		$multiple = $field['multiple'] ?? false;
Ok done

2024-09-07 03:15 UTC, rilwis requested changes

2024-09-07 03:15 UTC, rilwis commented on inc/clone.php
> +		$cleanup = $request->post( 'rwmb_cleanup' ); // Array of field ids
Chỗ này nên set `$request = rwmb_request()`. Và make sure `$cleanup` là array (có thể set giá trị default khi gọi hàm `post`).

2024-09-07 03:34 UTC, tanftw commented on inc/clone.php
> +		$cleanup = $request->post( 'rwmb_cleanup' ); // Array of field ids
Ok a, xong rồi nhé

2024-09-07 03:36 UTC, rilwis approved these changes

2024-09-07 03:36 UTC, merged